apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio.fullname" . }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "factorio.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: factorio-udp
      port: {{ .Values.service.ports.game }}
      targetPort: {{ .Values.service.ports.game }}
      protocol: UDP
    - name: factorio-rcon
      port: {{ .Values.service.ports.rcon }}
      targetPort: {{ .Values.service.ports.rcon }}
      protocol: TCP
