apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio.fullname" . }}
  labels:
    app: {{ template "factorio.name" . }}
    chart: {{ template "factorio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: factorio-udp
      port: {{ .Values.service.ports.game.port }}
      targetPort: {{ .Values.service.ports.game.port }}
      protocol: {{ .Values.service.ports.game.protocol | default "UDP" }}
    - name: factorio-tcp
      port: {{ .Values.service.ports.rcon.port }}
      targetPort: {{ .Values.service.ports.rcon.port }}
      protocol: {{ .Values.service.ports.rcon.protocol | default "TCP" }}
  selector:
    app: {{ template "factorio.name" . }}
    release: {{ .Release.Name }}
