namespace:
  create: true
  name: factorio

image:
  repository: factoriotools/factorio
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}
  ports:
    game:
      port: 34197
      protocol: UDP
    rcon:
      port: 27015
      protocol: TCP

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: factorio.brishencorp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: brishencorp-com-tls
      hosts:
        - factorio.brishencorp.com

persistence:
  enabled: true
  existingClaim: ""
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath: /var/lib/factorio
  reclaimPolicy: Retain
  annotations: {}
  labels: {}
