namespace:
  create: true
  name: factorio

image:
  repository: factoriotools/factorio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    game: 34197
    rcon: 27015

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - host: factorio.brishencorp.com
      paths:
        - path: /
          pathType: Prefix
          servicePort: 34197
  tls:
    - secretName: brishencorp-com-tls
      hosts:
        - factorio.brishencorp.com

persistence:
  enabled: true
  size: 5Gi
  storageClassName: factorio-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath: /var/lib/factorio
  reclaimPolicy: Retain

resources: {}

podSecurityContext: {}

securityContext: {}

auth:
  secretName: factorio-auth
  usernameKey: username
  tokenKey: token
